### ISSUE TITLE
code issues in slidingwindows_gradient.py and request for vignette

### ISSUE THREAD

**Issue by YiqianGu** [BoomStarcuc/GeneSegNet#4]
Dear authors,

Thanks for your effort! GeneSegNet truly impresses. 

However, when I attempted to utilize it with my personal data using the preset models, I encountered some small issues. In particular, in "slidingwindows_gradient.py," the code expects "image," "label," and "spot," while our folder names were created as "images," "labels," and "spots," causing issues at lines 248, 249, 250. Additionally, in line 304, I propose modifying the code to "spot_list.append([int(float(splits[0])), int(float(splits[1]))])" instead of "spot_list.append([int(float(splits[1])), int(float(splits[2]))])", as they should be x, y coordinates. Could you please validate these problems by testing on various datasets for resolution? 

Moreover, the current instructions seem a bit simplistic. After exploring GeneSegNet for several hours, I'm still uncertain about the specific output files it generates. Could you provide more comprehensive details regarding the output structure? Additionally, if possible, providing a vignette would be immensely helpful.

Thanks,
Yiqian

**Comment by BoomStarcuc** [comment]
Hi Yiqian,

Thank you very much for your interest in our work and for taking the time to explore GeneSegNet. We truly appreciate your valuable feedback and suggestions, which play a crucial role in improving our project.

I am grateful for pointing out the discrepancies in folder names and the coordinate issue in "slidingwindows_gradient.py." Your detailed observations have been immensely helpful. I have updated the GeneSegNet project to address the issues you've mentioned. The folder name expectations and the coordinates in the code have been revised. In addition, I also provided introductions about input and output structure in each step. Hope it can help you better understand our project.

Please do not hesitate to reach out if you have any more questions, encounter further issues, or have suggestions. Your feedback is always welcome and highly valued in our continuous effort to improve GeneSegNet.

Thanks,
Yuxing.

**Comment by YiqianGu** [comment]
Dear Yuxing,

Thanks for your reply and updates!

I also noticed a new typo in "slidingwindows_gradient.py" line 336, where it should be "# load input" . I have a few more questions:
1. Does the function of "slidingwindows_gradient.py" overlap with that of "GeneSeg_test.py"? It seems that "slidingwindows_gradient.py" handles the testing step and concatenates the divided patches. Can I skip "GeneSeg_test.py"?
2. For the outputs of "GeneSegslidingwindows_gradient.py", can I use "label_.png" as the mask and use it for Giotto or Seurat?
3. Will GeneSegNet generate the mapping relationships between individual transcripts and individual cell?

Thanks,
Yiqian

**Comment by BoomStarcuc** [comment]
Hi Yiqian,

Thank you for pointing out the typo in 'slidingwindows_gradient.py'. 

Regarding your questions:

1. The difference between "slidingwindows_gradient.py" and "GeneSeg_test.py" is that as you said, the output in "slidingwindows_gradient.py" is a full-resolution image that is stitched with all divided patches. Therefore, you can skip "GeneSeg_test.py" which outputs a prediction of each patch to generate full-resolution predicted results directly using "slidingwindows_gradient.py". 
2. The output of "slidingwindows_gradient.py" consists of "label_.png" and "label_.mat". For the format of their outputs, each cell corresponds to a unique ID (marked as a unique pixel value in a predicted mask), and the background is assigned a zero-pixel value, by doing so, we can identify each cell instance. Therefore, if you want to use it for Giotto or Seurat, I think you can convert the format that satisfies the requirements of Giotto or Seurat based on the current GeneSegNet output format.
3. I'm not entirely sure about the specific mapping relationships you're seeking, but I can assure you that GeneSegNet allows for the identification of individual transcripts corresponding to each cell. This is achieved by determining which transcript locations fall within a unique ID that presents a uniquely identified cell (Please see [section](https://github.com/BoomStarcuc/GeneSegNet/blob/master/README.md#find-the-mapping-relationships-between-transcripts-and-cells]) ).

Thanks
Yuxing.
